[package]
name = "life-universe-everything"
version = "0.1.0"
edition = "2024"

[dependencies]
argmin = "0.10.0"
eframe = "0.31.1"
egui_plot = "0.32.1"
json5 = "0.4.1"
serde = { version = "1.0.219", features = ["derive"] }
